CREATE DATABASE IF NOT EXISTS INSURANCE_DW;
CREATE SCHEMA IF NOT EXISTS INSURANCE_DW.RAW;

USE DATABASE INSURANCE_DW;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE CLAIMS_RAW (
    CLAIM_ID STRING,
    POLICY_ID STRING,
    CUSTOMER_ID STRING,
    CLAIM_AMOUNT NUMBER(12,2),
    CLAIM_STATUS STRING,
    EVENT_DATE DATE,
    UPDATED_AT TIMESTAMP_NTZ,
    BATCH_ID STRING,
    INGESTION_TIME TIMESTAMP_NTZ,
    SOURCE_FILE_NAME STRING
);
